# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ea4f3c0b0e520387f1c2b35ba16dae07c27a56fee945035465aa0a6d25ff29e897eb79ec18368e8bc88281f121add38d160f9eaf90aa96c54073daaaf97e5ba

test:
  secret_key_base: 6331a7d2e942379148c80148ceb88cb6742ce577d7acd6d6d5d31807fe11ddd9710dff468cb9fca913209837bb4ab57321c447ea9d0ac6038c66ba63030d7c43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
